server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://cdb-4g1maflw.bj.tencentcdb.com:10210/account_book?useSSL=false&autoReconnect=true
    username: root
    password: SZB9624995
    driverClassName: com.mysql.jdbc.Driver

data: this is the dev branch dev-config file of demo