server:
  port: 8080

data: this is the dev branch dev-config file of uac

logging:
  level:
    xin.shaozb.accountbook.uac.mapper: DEBUG

spring:
  datasource:
    url: jdbc:mysql://lcdb-4g1maflw.bj.tencentcdb.com:10210/account_book?useSSL=false
    username: root
    password: SZB9624995
    driverClassName: com.mysql.jdbc.Driver