server:
  port: 8080

data: this is the dev branch dev-config file of uac

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_book?useSSL=false
    username: root
    password: SZB9624995
    driverClassName: com.mysql.jdbc.Driver