server:
  port: 8001
spring:
  application:
    name: account-book-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chipmunkkk/account-book.git
          username: 1033780702@qq.com
          password: SZB9624995
          search-paths: account-book-config-repo
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: account-book-config

eureka:
  instance:
    hostname: 127.0.0.1
    port: 8000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/